name: Build and Push Docker Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the React
        run: |
          npm i
          npm  run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: delete an existing image 
        run: sudo docker rmi pathidocker/your-app-name:1 | true
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context:   
          push: true
          tags: pathidocker/your-app-name:1
          dockerfile: Dockerfile











































          
